// import localFont from "next/font/local";
// import Side from "@/components/Side";
// import Header from "@/components/Header";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Side/>
//         <Header/>

//         {children}
//       </body>
//     </html>
//   );
// }
"use client";  // Mark this component as client-side only

import { usePathname } from 'next/navigation';
import localFont from "next/font/local";
import Side from "@/components/Side";
import Header from "@/components/Header";
import "./globals.css";

// Define local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // List of routes where the header and sidebar should be hidden
  const noLayoutRoutes = ['/login', '/register'];

  const shouldShowLayout = !noLayoutRoutes.includes(pathname);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Conditionally render Sidebar and Header */}
        {shouldShowLayout && <Side />}
        {shouldShowLayout && <Header />}

        {/* Render the main content */}
        {children}
      </body>
    </html>
  );
}
